# Generated by Django 6.0 on 2025-12-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_is_popular_product_sales_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales_count',
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
